PROFILE_TTL_HOURS = 24 * 7
STATEMENTS_TTL_HOURS = 24
METRICS_TTL_HOURS = 24
PRICES_TTL_HOURS = 12
SEARCH_TTL_HOURS = 24 * 30
SEARCH_CACHE_SYMBOL = "__search__"
VALID_PRICE_RANGES = ("1y", "3y", "5y")
SEARCH_EXCHANGES = ("NASDAQ", "NYSE")
