# Generated by Django 6.0.3 on 2026-03-10 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('exchange', models.CharField(blank=True, max_length=20)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('ceo', models.CharField(blank=True, max_length=150)),
                ('website', models.URLField(blank=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('price_change', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_change_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('is_sp500', models.BooleanField(db_index=True, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stocks',
                'indexes': [models.Index(fields=['sector'], name='stocks_sector_88fdef_idx'), models.Index(fields=['name'], name='stocks_name_81639b_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=100)),
                ('params', models.JSONField(default=dict)),
                ('params_hash', models.CharField(max_length=32)),
                ('response_data', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'stock_cache',
                'indexes': [models.Index(fields=['symbol', 'endpoint'], name='stock_cache_symbol_5bb51d_idx'), models.Index(fields=['expires_at'], name='stock_cache_expires_36bae8_idx')],
                'unique_together': {('symbol', 'endpoint', 'params_hash')},
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
            options={
                'db_table': 'recently_viewed',
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'stock')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='stocks.stock')),
            ],
            options={
                'db_table': 'price_history',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', 'date'], name='price_histo_stock_i_cbdc34_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='KeyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10)),
                ('fiscal_year', models.IntegerField()),
                ('is_latest', models.BooleanField(db_index=True, default=False)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ps_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('pfcf_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('debt_to_equity', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('dividend_payout_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('gross_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('operating_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('net_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('fcf_per_share', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('revenue_per_share', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('roa', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('roic', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('enterprise_value', models.BigIntegerField(blank=True, null=True)),
                ('fcf_yield', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('current_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('earnings_yield', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('revenue_growth', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('net_income_growth', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('eps_growth', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('fcf_growth', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('net_income', models.BigIntegerField(blank=True, null=True)),
                ('free_cash_flow', models.BigIntegerField(blank=True, null=True)),
                ('operating_cash_flow', models.BigIntegerField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_metrics', to='stocks.stock')),
            ],
            options={
                'db_table': 'key_metrics',
                'indexes': [models.Index(fields=['stock', 'period'], name='key_metrics_stock_i_3512b0_idx'), models.Index(fields=['pe_ratio'], name='key_metrics_pe_rati_48b6e0_idx'), models.Index(fields=['dividend_yield'], name='key_metrics_dividen_066019_idx'), models.Index(fields=['roe'], name='key_metrics_roe_12fe40_idx'), models.Index(fields=['market_cap'], name='key_metrics_market__f649c3_idx'), models.Index(fields=['revenue_growth'], name='key_metrics_revenue_fb19dd_idx'), models.Index(fields=['net_margin'], name='key_metrics_net_mar_8547b5_idx'), models.Index(fields=['debt_to_equity'], name='key_metrics_debt_to_4e865d_idx'), models.Index(fields=['fcf_per_share'], name='key_metrics_fcf_per_96a6ea_idx')],
                'unique_together': {('stock', 'period', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_type', models.CharField(choices=[('income', 'Income Statement'), ('balance', 'Balance Sheet'), ('cashflow', 'Cash Flow Statement')], max_length=10)),
                ('period', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly')], max_length=10)),
                ('fiscal_year', models.IntegerField()),
                ('fiscal_quarter', models.CharField(blank=True, max_length=2, null=True)),
                ('data', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='stocks.stock')),
            ],
            options={
                'db_table': 'financial_statements',
                'indexes': [models.Index(fields=['stock', 'statement_type', 'period'], name='financial_s_stock_i_b7b87f_idx')],
                'unique_together': {('stock', 'statement_type', 'period', 'fiscal_year', 'fiscal_quarter')},
            },
        ),
        migrations.CreateModel(
            name='DCFCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('eps', 'EPS-Based'), ('fcf', 'FCF-Based')], max_length=3)),
                ('growth_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('discount_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('terminal_multiple', models.DecimalField(decimal_places=2, max_digits=6)),
                ('years_projected', models.IntegerField(default=10)),
                ('fair_value_result', models.DecimalField(decimal_places=4, max_digits=12)),
                ('current_price_at_save', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcf_calculations', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcf_calculations', to='stocks.stock')),
            ],
            options={
                'db_table': 'dcf_calculations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'stock'], name='dcf_calcula_user_id_ccd00b_idx')],
            },
        ),
    ]
